// GeometricTuple.scala
//
// This file contains a bunch of annoying non-variadic generic implementations of scala.TupleN[...] as GTTupleN[...].
// Note that this code was auto-generated by geotheorytuple_gen.py.
//

package org.plstudio.geometa.logic.context

trait GTTuple1[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  Tup <: Tuple1[
    A1
  ]
] extends GTBaseType[T] {}

trait GTTuple2[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  Tup <: Tuple2[
    A1,
    A2
  ]
] extends GTBaseType[T] {}

trait GTTuple3[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  Tup <: Tuple3[
    A1,
    A2,
    A3
  ]
] extends GTBaseType[T] {}

trait GTTuple4[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  Tup <: Tuple4[
    A1,
    A2,
    A3,
    A4
  ]
] extends GTBaseType[T] {}

trait GTTuple5[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  Tup <: Tuple5[
    A1,
    A2,
    A3,
    A4,
    A5
  ]
] extends GTBaseType[T] {}

trait GTTuple6[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  Tup <: Tuple6[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6
  ]
] extends GTBaseType[T] {}

trait GTTuple7[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  Tup <: Tuple7[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7
  ]
] extends GTBaseType[T] {}

trait GTTuple8[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  Tup <: Tuple8[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8
  ]
] extends GTBaseType[T] {}

trait GTTuple9[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  Tup <: Tuple9[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9
  ]
] extends GTBaseType[T] {}

trait GTTuple10[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  Tup <: Tuple10[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10
  ]
] extends GTBaseType[T] {}

trait GTTuple11[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  Tup <: Tuple11[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11
  ]
] extends GTBaseType[T] {}

trait GTTuple12[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  Tup <: Tuple12[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12
  ]
] extends GTBaseType[T] {}

trait GTTuple13[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  Tup <: Tuple13[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13
  ]
] extends GTBaseType[T] {}

trait GTTuple14[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  Tup <: Tuple14[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14
  ]
] extends GTBaseType[T] {}

trait GTTuple15[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  Tup <: Tuple15[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15
  ]
] extends GTBaseType[T] {}

trait GTTuple16[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  Tup <: Tuple16[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16
  ]
] extends GTBaseType[T] {}

trait GTTuple17[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  Tup <: Tuple17[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17
  ]
] extends GTBaseType[T] {}

trait GTTuple18[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  A18 <: GTBaseType[T],
  Tup <: Tuple18[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17,
    A18
  ]
] extends GTBaseType[T] {}

trait GTTuple19[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  A18 <: GTBaseType[T],
  A19 <: GTBaseType[T],
  Tup <: Tuple19[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17,
    A18,
    A19
  ]
] extends GTBaseType[T] {}

trait GTTuple20[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  A18 <: GTBaseType[T],
  A19 <: GTBaseType[T],
  A20 <: GTBaseType[T],
  Tup <: Tuple20[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17,
    A18,
    A19,
    A20
  ]
] extends GTBaseType[T] {}

trait GTTuple21[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  A18 <: GTBaseType[T],
  A19 <: GTBaseType[T],
  A20 <: GTBaseType[T],
  A21 <: GTBaseType[T],
  Tup <: Tuple21[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17,
    A18,
    A19,
    A20,
    A21
  ]
] extends GTBaseType[T] {}

trait GTTuple22[
  T <: GeomTheory,
  A1 <: GTBaseType[T],
  A2 <: GTBaseType[T],
  A3 <: GTBaseType[T],
  A4 <: GTBaseType[T],
  A5 <: GTBaseType[T],
  A6 <: GTBaseType[T],
  A7 <: GTBaseType[T],
  A8 <: GTBaseType[T],
  A9 <: GTBaseType[T],
  A10 <: GTBaseType[T],
  A11 <: GTBaseType[T],
  A12 <: GTBaseType[T],
  A13 <: GTBaseType[T],
  A14 <: GTBaseType[T],
  A15 <: GTBaseType[T],
  A16 <: GTBaseType[T],
  A17 <: GTBaseType[T],
  A18 <: GTBaseType[T],
  A19 <: GTBaseType[T],
  A20 <: GTBaseType[T],
  A21 <: GTBaseType[T],
  A22 <: GTBaseType[T],
  Tup <: Tuple22[
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    A11,
    A12,
    A13,
    A14,
    A15,
    A16,
    A17,
    A18,
    A19,
    A20,
    A21,
    A22
  ]
] extends GTBaseType[T] {}

